Infodate/urls.py
from django.conf.urls import url
# from .import views
from .views import calcul, engine, index, input_new
app_name = 'Infodate'

urlpatterns = (
	url(r'^$', index, name='index'),
	url(r'^/InfodateCalcul/', calcul, name='calcul'),
	url(r'^/InfodateEngine/', engine, name='engine'),
    url(r'^/InfodateInput/', input_new, name='input_new'),
)

login_auth/urls.py
from django.conf.urls import url
from login_auth import views as login_views
# from django.conf import settings

urlpatterns = [
    url(r'^login/$', login_views.login, name='login'),
    url(r'^logout/$', login_views.logout, name='logout')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
	url(r'^', include('Infodate.urls')),
	path(r'admin/', admin.site.urls),
]

Infodate/models.py
from django.db import models
from django.utils import timezone

STATUS_CHOICES_TYPE = (
	('новый', 'новый'),
	('б/у', 'б/у'),
)

STATUS_CHOICES = (
	('да', 'да'),
	('нет', 'нет'),
)

STATUS_CHOICES_ENG = (
	('K7J', '1,4л/75л.с.(K7J)'),
	('K7M7101', '1,6л/82л.с.(K7M710)'),
	('K7M710', '1,6л/86л.с.(K7M710)'),
	('K7M800', '1,6л/102л.с.(K7M800)'),
	('K7M801', '1,6л/113л.с.')
)

STATUS_CHOICES_KPP = (
	('akpp', 'АКПП'),
	('mkpp', 'МКПП'),
)
class Infodate(models.Model):
	author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
	probeg_tek = models.CharField(max_length=8)
	date_create = models.DateField(auto_now=False)
	probeg_all = models.CharField(max_length=8)
	date_publish = models.DateTimeField(auto_now_add=True)
	conder = models.CharField(max_length=3, choices = STATUS_CHOICES, default='да')
	type_expl = models.CharField(max_length=5, choices = STATUS_CHOICES_TYPE, default='новый')
	type_engine = models.CharField(max_length=20, choices = STATUS_CHOICES_ENG, default='K7J')
	type_kpp = models.CharField(max_length=4, choices = STATUS_CHOICES_KPP, default='mkkp')
	date_oil_last = models.DateField(auto_now=False)
	date_liq_last = models.DateField(auto_now=False)
	date_brake_last = models.DateField(auto_now=False)
	date_to_last = models.DateField(auto_now=False)
	to_make = models.CharField(max_length=3, choices = STATUS_CHOICES, default='да')	
	
def publish(self):
	self.date_publish = timezone.now()
	self.save()

def _str_(self):
	return self.probeg_tek, self.probeg_all, self.conder



# Create your models here.

login_auth/models.py
from django.db import models

# Create your models here.

Infodate/forms.py
from django import forms
from .models import Infodate

class InfodateForm(forms.ModelForm):

    class Meta:
        model = Infodate
        fields = ('date_create', 'type_engine', 'type_kpp', 'probeg_tek', 'probeg_all', 'type_expl', 'date_oil_last', 'date_liq_last', 'date_brake_last', 'date_to_last', 'to_make', 'conder',)

Infodate/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Infodate
from .forms import InfodateForm

def index(request):
    #	primer1 = Infodate.objects.all().filter(conder = 'нет')
    return render(request, 'Infodate/index.html', {})


def calcul(request):
    calculat = Infodate.objects.all().filter(conder='да')
    return render(request, 'Infodate/calcul.html', {'calculat': calculat})


def engine(request):
    return render(request, 'Infodate/engine.html', {})

def input_new(request):
    if request.method == "POST":
        form = InfodateForm(request.POST)
        if form.is_valid():
            infodate = form.save(commit=False)
            infodate.author = request.user
            infodate.date_publish = timezone.now()
            infodate.save()
            return calcul(request)
#            return redirect('calcul', pk=infodate.pk)
    else:
        form = InfodateForm()
    return render(request, 'Infodate/input_edit.html', {'form': form})


#	def index(request):
#	infodates = Infodate.objects.all().filter(conder = 'нет')
#	return render(request, 'Infodate/index.html',{'infodates': infodates})


# def primer(request):
#    primer1 = Infodate.objects.all().order_by('date_publish')
# 	return render(request, 'Infodate/primer.html',{'primer1':primer1})
# Create your views here.

login_auth/views.py
from django.shortcuts import render, get_object_or_404  # render page, return data or 404 page
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import auth

def login(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get('username',"")
        password = request.POST.get('passwors',"")
        user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/')
    else:
        login_error = "User not exist"
        context = {"login_error": login_error}
        return render(request, 'login_auth/login.html', context)
    else:
        return render(request, 'login_auth/login.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

# Create your views here.

mysite/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'Infodate/index.html',{})
# Create your views here.

Infodate/templates/Infodate/calcul.html
<!doctype html>
<html lang="ru">
<head>
 <meta charset="UTF-8">
 <title>Техническая поддержка Renault Logan</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
 <link rel="stylesheet" href="{% static 'CSS/menu.css' %}">
 <meta charset="UTF-8">
</head>

 <body style="background-color: #FFFFFF; overflow-x: hidden">
  <div id="conteiner">
  <div id="header">
    <div id="namecontenier">	
		<div id="name">
			Техническое сопровождение по эксплуатации автомобиля<br>&#34;Renault Logan&#34;
		</div>
		<div id="logo"></div>
		<div id="videologan">
			<video width="250px" autoplay loop>
				<source src='{% static "VIDEO/logan.mp4" %}' type="video/mp4">
			</video>
		</div>
	  </div>
  </div>
  <div id="menu">
    <ul id="nav">
		 <li class="left"><a href="{% url 'Infodate:index'%}" target="_blank">Домой</a></li>
		 <li class="right"><a href="{% url 'Infodate:engine' %}" target="_blank">Узлы</a></li>
		 <li class="left"><a href="#">Service</a></li>
		 <li class="right"><a href="#">Карта СТО</a></li>
		 <li class="left"><a href="#">Литература</a></li>
		 <li class="right"><a href="{% url 'Infodate:calcul' %}" target="_blank">Расчет</a>
		 </li>
    </ul>
  </div>
  <div id="osnova">
    <div>
		{% for i in calculat %}	
			<table style="text-align:center; border: 1px dashed #1240AA">
				<tr>
					<th>Имя<br>пользователя</th><th>текущий<br>пробег</th><th>дата<br>приобретения</th>
					<th>общий<br>пробег</th><th>дата<br>публикации</th><th>наличие<br>кондиционера</th>
				</tr>
				<tr></tr>
				<tr>
					<td>{{i.author}}</td><td>{{i.probeg_tek}}</td><td>{{i.date_create}}</td>
					<td>{{i.probeg_all}}</td><td>{{i.date_publish}}</td><td>{{i.conder}}</td>
				</tr>
				<tr></tr>
			</table>
		{% endfor %}
	</div>
	<div>
		<!--a href="{% url 'Infodate:input_new' %}"><span class="glyphicon glyphicon-plus"></span></a-->
		<h1><a href="{% url 'Infodate:input_new' %}">Расчитать данные</a></h1>
	</div>
  </div>
  <div class="footer">
  	
  </div>
 </div>
</body>
</html>

Infodate/templates/Infodate/engine.html
<!doctype html>
<html>
<head>
    <meta charset="windows-1251">
    <title>engine</title>
    {% load staticfiles %}
    <link href="{% static 'CSS/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'CSS/menu.css' %}" rel="stylesheet" type="text/css">

</head>

<body style="background-color: #FFFFFF; overflow-x: hidden">
 <div id="conteiner"> 
  <div id="header">
    <div id="namecontenier">	
		<div id="name">
			Техническое сопровождение по эксплуатации автомобиля<br>&#34;Renault Logan&#34;
		</div>
		<div id="logo"></div>
		<div id="videologan">
			<video width="250px" autoplay loop>
				<source src='{% static "VIDEO/logan.mp4" %}' type="video/mp4">
			</video>
		</div>
	  </div>
   </div>
   <div id="menu">
		<ul id="nav">
		 <li class="left"><a href="{% url 'Infodate:index'%}" target="_blank">Домой</a></li>
		 <!--li class="right"><a href="{% url 'Infodate:engine' %}" target="_blank">Узлы</a></li-->
		 <li class="left"><a href="#">Service</a></li>
		 <li class="right"><a href="#">Карта СТО</a></li>
		 <li class="left"><a href="#">Литература</a></li>
		 <li class="right"><a href="{% url 'Infodate:calcul' %}" target="_blank">Расчет</a>
		 </li>
    </ul>
   </div>
  <div id="osnova">
   	<!--div class="vmenu">
      <ul style="margin-top: 10px;">
         <li>
             <a class="entypo-menu" href="#"></a> <span class="menu">Menu</span>
         </li>
         <li>
             <a class="entypo-star" href="#"></a> <span>Favorite</span>
         </li>
         <li>
             <a class="entypo-newspaper" href="#"></a> <span>About us</span>
         </li>
         <li>
             <a class="entypo-location" href="#"></a> <span>Find us</span>
         </li>
         <li>
             <a class="entypo-link" href="#"></a> <span>Share</span>
         </li>
         <li>
             <a class="entypo-help-circled" href="#"></a> <span>FAQ's</span>
         </li>
      </ul>
    </div-->
    <div class= "logan_body">
       <img src={% static "IMAGE/loganchema/logan.png" %}  width="100%" height="100%" usemap="#loganmap" alt="Модель автомобиля"/>
	   <map name="loganmap" >
	     <area shape="rect" coords="100,200,180,280" alt="Двигатель" href="#modalENGINE">
		 <area shape="circle" coords="70,300,40" alt="Электрика" href="#modalELECT">
		 <area shape="rect" coords="150,300,250,380" alt="Трансмиссия" href="#modalTRANSMISS">
	   </map>
    </div>

    <div class="modal">
     <!--a href="#modalONE" class="open">Открыть окно</a-->
      <div class="modal_engine" id="modalENGINE">
          <div class="title">Двигатель</div>
             <a href="#" title="Закртыть" class="close">X</a>
      </div>
    </div>
    <div class="modal">
      <!--a href="#modalTWO" class="open">Открыть окно</a-->
        <div class="modal_elect" id="modalELECT">
              <div class="title">Электрика</div>
                <a href="#" title="Закртыть" class="close">X</a>
        </div>
    </div>
    <div class="modal">
      <!--a href="#modalTWO" class="open">Открыть окно</a-->
        <div class="modal_transmiss" id="modalTRANSMISS">
              <div class="title">Трансмиссия</div>
                <a href="#" title="Закртыть" class="close">X</a>
        </div>
    </div>

  </div>
  <div class="footer">

  </div>
 </div> 
</body>
</html>

Infodate/templates/Infodate/index.html
<!doctype html>
<html lang="ru">
<head>
 <meta charset="UTF-8">
 <title>Техническая поддержка Renault Logan</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
 <link rel="stylesheet" media="screen" href="{% static 'CSS/menu.css' %}">
 <!--<script type="text/javascript" src="{% static 'js/openwindow.js' %}"></script>-->
 <meta charset="UTF-8">
 <style type="text/css">
        table th, table td
        {
            padding: 0px;
        }
        table img
        {
            height: 480px;
            width: 850px;
        }
    </style>
</head>

<body style="background-color: #FFFFFF; overflow-x: hidden">
 <div id="conteiner">
	<div id="header">
	  <div id="namecontenier">	
		<div id="name">
			Техническое сопровождение по эксплуатации автомобиля<br>&#34;Renault Logan&#34;
		</div>
		<div id="logo"></div>
		<div id="videologan">
			<!--iframe width="250px" height="145px" src="https://www.youtube.com/embed/bzsFeDt8hf4? start=0 autoplay=1 playlist=bzsFeDt8hf4 loop=1 controls=0 disablekb=1 showinfo=0 rel=0" frameborder="0" allowfullscreen></iframe-->
			<video width="250px" autoplay loop>
				<source src='{% static "VIDEO/logan.mp4" %}' type="video/mp4">
			</video>
		</div>
	  </div>
   </div>
	  <div id="menu">
		<ul id="nav">
			<!--li class="left"><a href="#">About</a></li-->
			<li class="right"><a href="{% url 'Infodate:engine' %}" target="_blank">Узлы</a></li>
			<li class="left"><a href="#">Service</a></li>
			<li class="right"><a href="#">Карта СТО</a></li>
			<li class="left"><a href="#">Литература</a></li>
			<li class="right"><a href="{% url 'Infodate:calcul' %}" target="_blank">Расчет</a></li>
		</ul>
      </div>
   <div id="osnova">
    
    <!--div class="hyst">
 	   <div  class="hystory"> <!--style="font-family: Helvetica Neue; font-size: 14px"-->
  	      <!--h4 align="center">Краткая история создания<br>автомобиля Renault Logan </h4>
	   </div>
	   <div class="hystory_txt">
  	    <hr style="align: center; width: 250px; size: 1px;">	 
		 <i>
		   <p align="justify"> Компактный седан Renault Logan, он же Dacia Logan, дебютировал в 2004 году.
           		               Производство автомобилей для российского рынка началось в апреле 2005 года
							   на московском «Автофрамосе».<br>
		                       &#160;Российский «Логан» оснащался бензиновыми моторами объемом 1,4 (75 л. с.) 
		                       и 1,6 (84 или 102 л. с.) литра в сочетании с механической или автоматической 
							   коробками передач.<br>
							   &#160;Первоначально машина предлагалась по цене 8999 долларов, 
							   а в 2015 году базовая версия стоила уже 399 тысяч рублей.<br>
		                       &#160;Производство седанов первого поколения в России завершилось 18 декабря 2015 года, 
		                       всего за десять лет московский завод выпустил около 550 тысяч таких машин.<br>
		                       &#160;На базе «Логана» также созданы хэтчбек Sandero, универсал «Лада Ларгус», 
		                       пикап Nissan NP200. В Индии эта модель производится под маркой Mahindra, 
							   а в Иране «Рено» выпускается до сих пор.
		   </p>
		 </i>
	   </div>  
    </div-->
	<div>
		<img class="mean" src='{% static "IMAGE/speedometr.jpg" %}'>
	</div>
	<div class="logan3d">
		<table border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td>
                <img src="" id="product1" />
            </td>
          </tr>
        </table>
		<div id="dvImages" style="display: none">
			<img src='{% static "IMAGE/3D_new/1.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/2.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/3.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/4.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/5.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/6.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/7.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/8.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/9.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/10.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/11.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/12.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/13.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/14.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/15.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/16.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/17.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/18.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/19.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/20.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/21.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/22.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/23.jpg" %}'>
			<img src='{% static "IMAGE/3D_new/24.jpg" %}'>
		</div>
	</div>
	<div>
		<img id="gradus" src='{% static "IMAGE/360.png" %}'>
	</div>
   <!--div class= "logan_body">
       <img src='{% static "IMAGE/logan.png" %}'  width="100%" height="100%" usemap="#loganmap" alt="Модель автомобиля"/>
	   <map name="loganmap" >
	     <area shape="rect" coords="100,200,180,280" alt="Двигатель" href="#modalENGINE">
		 <area shape="circle" coords="70,300,40" alt="Электрика" href="#modalELECT">
		 <area shape="rect" coords="150,300,250,380" alt="Трансмиссия" href="#modalTRANSMISS">
	   </map>
   </div-->
   
   <!--div class="modal">
      <div class="modal_engine" id="modalENGINE"> 
          <div class="title">Двигатель</div> 
             <a href="#" title="Закртыть" class="close">X</a> 
      </div> 
    </div> 
    <div class="modal">
        <div class="modal_elect" id="modalELECT"> 
              <div class="title">Электрика</div> 
                <a href="#" title="Закртыть" class="close">X</a> 
        </div> 
    </div>
    <div class="modal"> 
      <!--a href="#modalTWO" class="open">Открыть окно</a--> 
        <!--div class="modal_transmiss" id="modalTRANSMISS"> 
              <div class="title">Трансмиссия</div> 
                <a href="#" title="Закртыть" class="close">X</a> 
        </div> 
    </div>
   
   <!--div id="rjad">
        <div id="Vyvod" style="margin-left: 50px; top: 0px;">   </div>
        <div id="Vyvod"style="margin-left: 350px; top: -80px;">   </div>
		<div id="Vyvod" style="margin-left: 650px; top: -160px;"> </div>
   </div-->     
  </div>
  <div id="footer">
  	
  </div>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/matdumsa/jQuery.threesixty/master/jquery.threesixty.js"></script>
    <script type="text/javascript">
        $(function () {
            //Load the image URLs into an Array.
            var arr = new Array();
            $("#dvImages img").each(function () {
                arr.push($(this).attr("src"));
            });

            //Set the first image URL as source for the Product.
            $("#product1, #product2, #product3").attr("src", arr[0]);

            //Click mode.
            $("#product1").threesixty({ images: arr,
                method: 'click',
                sensibility: 2
            });
        });
    </script>
 </div>	
</body>
</html>


Infodate/templates/Infodate/input_edit.html
<!doctype html>
<html lang="ru">
<head>
 <meta charset="UTF-8">
 <title>Техническая поддержка Renault Logan</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="{% static 'CSS/style.css' %}">
 <link rel="stylesheet" href="{% static 'CSS/menu.css' %}">
 <meta charset="UTF-8">
</head>

<body style="background-color: #FFFFFF; overflow-x: hidden">
 <div id="conteiner">
  <div id="header">
    <div id="namecontenier">	
		<div id="name">
			Техническое сопровождение по эксплуатации автомобиля<br>&#34;Renault Logan&#34;
		</div>
		<div id="logo"></div>
		<div id="videologan">
			<video width="250px" autoplay loop>
				<source src='{% static "VIDEO/logan.mp4" %}' type="video/mp4">
			</video>
		</div>
	  </div>
  </div>
  <div id="menu">
    <ul id="nav">
		 <li class="left"><a href="{% url 'Infodate:index'%}" target="_blank">Домой</a></li>
		 <li class="right"><a href="{% url 'Infodate:engine' %}" target="_blank">Узлы</a></li>
		 <li class="left"><a href="#">Service</a></li>
		 <li class="right"><a href="#">Карта СТО</a></li>
		 <li class="left"><a href="#">Литература</a></li>
		 <li class="right"><a href="{% url 'Infodate:calcul' %}" target="_blank">Расчет</a>
		 </li>
    </ul>
  </div>
  <div id="osnova">
    <div>
		{% block content %}
   			<h1>New post</h1>
    			<form method="POST">{% csrf_token %}
        			{{ form.as_p }}
        			<button type="submit" class="save btn btn-default">Save</button>
    			</form>
		{% endblock %}
	</div>
	<div>
		{% for i in calculat %}	
			<table style="text-align:center; border: 1px dashed #1240AA">
				<tr>
					<th>Имя<br>пользователя</th><th>текущий<br>пробег</th><th>дата<br>приобретения</th>
					<th>общий<br>пробег</th><th>дата<br>публикации</th><th>наличие<br>кондиционера</th>
				</tr>
				<tr></tr>
				<tr>
					<td>{{i.author}}</td><td>{{i.probeg_tek}}</td><td>{{i.date_create}}</td>
					<td>{{i.probeg_all}}</td><td>{{i.date_publish}}</td><td>{{i.conder}}</td>
				</tr>
				<tr></tr>
			</table>
		{% endfor %}
	</div>
  </div>
  <div class="footer">
  	
  </div>
 </div>
</body>
</html>

login_auth/templates/login.html
{% block login_auth %}
<div>
	<form action="/login/" method="POST">
	{% csrf_token %} # защита
		<label for="username">User name</label>
		<input type="text" name="username" id="username">
		<label for="password">Password</label>
		<input type="password" name="password" id="password">
	{% if login_error %} # если вышла ошибка или такой пользователь не существует
		<label class="error">{{ login_error }}</label>
	{% endif %}
		<input type="submit" value="Log in">
	</form>
</div>
{% endblock login_auth %}